module.exports = {
    SELECT_YOU: "Are You",
    GUIDE1: "Swipe right to like a candidate\nSwipe Left to pass",
    GUIDE2: "It's a Match when your candidate\nalso swipes right for you.",
    GUIDE3: "Once you've matched, you can chat\nwith each other.",
    NOW_FINDING: "Now Finding...",
    //Setting
    SETTING_SEARCH: "Search settings",
    SETTING_HEADER_OFFER: "Job offer",
    SETTING_HEADER_CANDIDATE: "Candidate",
    SETTING_HEADER_WORK: "Work",
    SETTING_HEADER_LEADER: "Leader",
    SETTING_HEADER_APP: "App settings",
    //Setting-Work
    SETTING_TYPE: "Type of work",
    SETTING_FIELD_WORK: "Field of work",
    SETTING_FIELD: "Field (function or industry)",
    SETTING_JOB: "Job title",
    SETTING_DESIRED_JOB: "Desired job title",
    SETTING_EXPECTED_SALARY: "Expected salary range",
    SETTING_MONTHLY_SALARY: "Monthly salary range",
    SETTING_SALARY_UNIT: "THB",
    //Setting-Leader
    SETTING_LEADER_EXPERIENCE: "Leader's years of experience",
    SETTING_YEARS: "Years",
    SETTING_LEADER_SKILLS: "Leader skills",
    SETTING_LEADER_AGE: "Desired leader age",
    SETTING_LEADER_GENDER: "Desired leader gender",
    SETTING_LEADER_NATIONALITY: "Leader nationality",
    SETTING_DISTANCE: "Distance",
    SETTING_LOCATION: "Choose Location",
    //Setting-Candidate
    SETTING_CANDIDATE_EXPERIENCE: "Candidate years of experience",
    SETTING_CANDIDATE_SKILLS: "Candidate skills",
    SETTING_CANDIDATE_AGE: "Desired candidate age",
    SETTING_CANDIDATE_GENDER: "Desired candidate gender",
    SETTING_CANDIDATE_NATIONALITY: "Candidate nationality",
    //App Settings
    SETTING_FONT: "Font size",
    SETTING_LANGUAGE: "Language",
    //Edit Info
    EDIT_ABOUT: "About",
    EDIT_CONTACT_INFO: "Contact Information",
    EDIT_CURRENT_WORK: "Current Work",
    EDIT_CURRENT_SALARY: "Current Salary",
    EDIT_COMPANY: "Company",
    EDIT_EDUCATION: "Education Institute",
    EDIT_SKILLS: "My skills",
    EDIT_DEGREE: "Degree",
    EDIT_GENDER: "Gender",
    EDIT_AGE: "Age",
    EDIT_SHOW_EDUCATION: "Don't show my education",
    EDIT_SHOW_AGE: "Don't show my age",
};